export const RoutePath = Object.freeze({
  HOME: "/",
  EVENTS: "/events",
  BOOKING: "/booking",
  PAYMENT: "/payment",
  AUTH: "/auth",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  OTP: "/auth/otp",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  DASHBOARD: "/dashboard",
  ADMIN_DASHBOARD: "/dashboard/admin",
  ORGANIZER_DASHBOARD: "/dashboard/organizer",
  ATTENDEE_DASHBOARD: "/dashboard/attendee",
});
